---

    - name: APT repository.
      apt_repository:
        repo: "{{apt_source_config.0.source}}"
        state: "{{ apt_source_config.0.state|default('present') }}"

   # Update APT package lists
    - apt: update_cache=yes
