---

- name: Override vars for PPAs.
  include_vars: ppa.yml
  when: apt_source_source_string.startswith("ppa:")


# see apt_preferences manpage. 200 is a good choice because it means lower
# than the default repo priority (500) but higher than installed (100) so
# when a package from the source is installed, it will still get upgraded.
- name: Set repo packages to low priority.
  template:
    src: preferences.j2
    dest: "{{ item.filepath|default(apt_source_preferences_filepath) }}{{ item.pattern|regex_replace('[^A-Za-z0-9]', '')}}"
    owner: root
    group: root
    mode: 0644
  # debug: var=item
  with_items:
    - "{{ apt_source_default_pin }}"
    - "{{ apt_source_packages }}"
  when: apt_source_state != "absent"

- name: Remove package pins.
  file:
    path: "{{ item.filepath|default(apt_source_preferences_filepath) }}{{ item.pattern|regex_replace('[^A-Za-z0-9]', '')}}"
    state: absent
  with_items:
    - "{{ apt_source_default_pin }}"
    - "{{ apt_source_packages }}"
  when: apt_source_state == "absent"

- name: Remove package pins (source kept).
  file:
    path: "{{ item.filepath|default(apt_source_preferences_filepath) }}{{ item.pattern|regex_replace('[^A-Za-z0-9]', '')}}"
    state: absent
  when: apt_source_state != "absent" and item.absent is defined
  with_items:
    - "{{ apt_source_default_pin }}"
    - "{{ apt_source_packages }}"
