---
- name: Apt key (url).
  apt_key:
    url: "{{ apt_source_key.url }}"
    id: "{{ apt_source_key.id }}"
    state: "{{ apt_source_state }}"
  when: apt_source_key.url is defined


- name: Apt key (keyserver).
  apt_key:
    keyserver: "{{apt_source_key.keyserver}}"
    id: "{{apt_source_key.id}}"
    state: "{{ apt_source_state }}"
  when: apt_source_key.keyserver is defined