---
# tasks file for debian_repo

- include: apt-key.yml
  when: apt_source_config.0.source_string is defined
    and not apt_source_config.0.source_string.startswith("ppa:")

- include: apt-repo.yml

- include: apt-pin.yml
